import { Ecs } from '../../generated';

const ecs = {} as Ecs;

/**
 * This an example use of the autogenerated definition files.
 * As an integration test, we run the tsc on this post-generation.
 */

ecs.trace.id;
ecs['@timestamp'];
ecs.message;
ecs.event?.category;
ecs.threat?.indicator.marking.tlp;
