import { Ecs } from '../../generated';

const ecs = {} as Ecs;

/**
 * This an example use of the autogenerated definition files
 */

ecs.trace.id;
ecs['@timestamp'];
ecs.message;
ecs.event?.category;
ecs.threat?.indicator.marking.tlp;
